### ISSUE TITLE
Compilation failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by pludov** [lassik/shm_open_anon#1]
Hello !

I am trying to use your lib to get memfd_create emulation on system where it is not directly supported. However on Ubuntu 16.04, compilation fails with error: ‘MFD_CLOEXEC’ undeclared.

Full details of the build:
https://travis-ci.org/pludov/mobindi/jobs/564185188#L1

**Comment by lassik** [comment]
Thanks for reporting the bug, I'm very happy that some people are finally finding this library :) I wonder if we need to add an include file. Possibly `#include <sys/memfd.h>`. Does `grep -Rin MFD_CLOEXEC /usr/include` on an Ubuntu 16.04 system give you any useful matches?

**Comment by pludov** [comment]
sys/memfd.h is missing on that distro.
However,  the constant can be found in linux/memfd.h


Le 27 juillet 2019 09:43:00 GMT+02:00, Lassi Kortela <notifications@github.com> a écrit :
>Thanks for reporting the bug, I'm very happy that some people are
>finally finding this library :) I wonder if we need to add an include
>file. Possibly `#include <sys/memfd.h>`. Does `grep -Rin MFD_CLOEXEC
>/usr/include` on an Ubuntu 16.04 system give you any useful matches?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lassik/shm_open_anon/issues/1#issuecomment-515662448

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by lassik** [comment]
Tried including `<linux/memfd.h>` on Debian testing and Void Linux. No problems, so let's add it in! Does this fix your build on Ubuntu 16.04?

**Comment by pludov** [comment]
It's working now, thank you !
