### ISSUE TITLE
Generate tempfile name from current time and pid

### ISSUE THREAD

**Issue by lassik** [lassik/shm_open_anon#2]
Opening `/dev/random` is a bit of a heavyweight way to generate randomness for our purposes, since we only need that randomness for a split second to ensure a unique filename. It could work to get "randomness" from something like `clock_gettime(CLOCK_MONOTONIC, &tv); random_number = tv.tv_sec + tv.tv_nsec + getpid();` and then convert that number to ASCII.

**Comment by pludov** [comment]
Maybe you could use /dev/random once and keep incrementing the result for subsequent uses.

**Comment by lassik** [comment]
That would work. In principle it's not thread-safe but I'm not sure it matters since this is just random data and we have the `O_EXCL` safeguard to prevent collisions when all else fails. `getpid()` or `clock_gettime()` would be the fastest and simplest syscalls, that's why I thought of them. But the code to unpack the digits might be more complex than using `/dev/random`.

**Comment by lassik** [comment]
I tried the time+pid approach on all supported operating systems and it works without problems, so I merged it into master. Let me know in case there are any problems.

**Comment by pludov** [comment]
getpid could still have trouble if using from a multithreaded program (two threads will share the same pid and will only have gettime to distinguish).

**Comment by lassik** [comment]
I thought about that. Instead of the process ID, we could get the thread ID. But I don't know how portable something like `pthread_self()` is. Since `clock_gettime()` returns a nanosecond counter, I hope that will be enough to differentiate between threads. No computer keeps time accurate to a nanosecond, but I hope the real resolution will be precise enough that two threads calling `clock_gettime()` cannot get the exact the same `tv_sec + tv_nsec` value.

At this point I ran out of ideas for more entropy sources. Maybe something like `getrusage()` or some portable way to get a CPU cycle counter? Any new ideas, please let me know :)

**Comment by pludov** [comment]
I think you should just use any random source on first call (pid + clock seems fine), then for subsequent call keep incrementing a volatile int to generate .

`    int shm_id = __atomic_add_fetch(&shm_count, 1, __ATOMIC_SEQ_CST);
`
(This is part of the C11 standard)

**Comment by lassik** [comment]
That's a good idea. However, C11 is quite new and some systems have older compilers. NetBSD, Solaris, Haiku and any upcoming Windows emulation ports (msys, cygwin) cause concern in particular. I can verify by hand whether all of them have `__atomic_add_fetch` in the system default compiler (for Solaris I test on a OmniOS VM which has gcc), but a more "classic" way to increment a counter might be nicer. Would this cause problems:

```
static unsigned long get_unique_count() {
    static volatile unsigned long global_counter = 0;
    return global_counter++;
}
```

I.e. do you know whether `global_counter++` is guaranteed atomic or not?

**Comment by lassik** [comment]
Another option is simply to check after the `shm_open()` call that `if (fd == -1) if (errno == EEXIST) goto again;`

**Comment by pludov** [comment]
You are right, that's the way to go !

Le 29 juillet 2019 14:16:37 GMT+02:00, Lassi Kortela <notifications@github.com> a écrit :
>Another option is simply to check after the `shm_open()` call that `if
>(fd == -1) if (errno == EEXIST) goto again;`
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/lassik/shm_open_anon/issues/2#issuecomment-515966795

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by lassik** [comment]
What do you think about this: bfc7dbf

**Comment by pludov** [comment]
Looks good to me !

Le 29 juillet 2019 15:29:32 GMT+02:00, Lassi Kortela <notifications@github.com> a écrit :
>What do you think about this: bfc7dbf
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/lassik/shm_open_anon/issues/2#issuecomment-515991550

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.
